package movies.emfstore.util;

public enum EMFStoreRequest {
	GET_MOVIES, LOAN_MOVIE, RETURN_MOVIE, GET_EPISODES, GET_SEASONS, GET_SERIES, LOAN_EPISODE, LOAN_SEASON, LOAN_SERIES, RETURN_SERIES, RETURN_SEASON, RETURN_EPISODE;
}
